# Generated by Django 2.2.1 on 2019-07-02 05:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('current', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hadron', '0001_initial'),
        ('propagator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meson2pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('momentum', models.SmallIntegerField(help_text='SmallInt: Total momentum in units of 2 pi / L')),
                ('propagator0', models.ForeignKey(help_text='ForeignKey: Pointer to first propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='ForeignKey: Pointer to second propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sink', models.ForeignKey(help_text='ForeignKey: Pointer to sink interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hadron.Hadron')),
                ('source', models.ForeignKey(help_text='ForeignKey: Pointer to source interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hadron.Hadron')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.CreateModel(
            name='BaryonFH3pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('momentum', models.SmallIntegerField(help_text='SmallInt: Sink momentum in units of 2 pi / L')),
                ('fhpropagator', models.ForeignKey(help_text='Foreign Key pointing to Feynman-Hellmann propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator0', models.ForeignKey(help_text='Foreign Key pointing to spectator propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='Foreign Key pointing to spectator propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sink', models.ForeignKey(help_text='Foreign Key pointing to sink operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hadron.Hadron')),
                ('source', models.ForeignKey(help_text='Foreign Key pointing to source operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hadron.Hadron')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.CreateModel(
            name='Baryon4DSeq3pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('current', models.ForeignKey(help_text='Foreign Key to current interaction operator', on_delete=django.db.models.deletion.CASCADE, to='current.Current')),
                ('propagator0', models.ForeignKey(help_text='Foreign Key pointing to spectator propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='Foreign Key pointing to spectator propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('seqpropagator', models.ForeignKey(help_text='Foreign Key pointing to sequential propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('source', models.ForeignKey(help_text='Foreign Key pointing to source operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hadron.Hadron')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.AddConstraint(
            model_name='meson2pt',
            constraint=models.UniqueConstraint(fields=('propagator0', 'propagator1', 'source', 'sink', 'momentum'), name='unique_correlator_meson2pt'),
        ),
        migrations.AddConstraint(
            model_name='baryonfh3pt',
            constraint=models.UniqueConstraint(fields=('source', 'fhpropagator', 'propagator0', 'propagator1', 'sink', 'momentum'), name='unique_correlator_baryonfh3pt'),
        ),
        migrations.AddConstraint(
            model_name='baryon4dseq3pt',
            constraint=models.UniqueConstraint(fields=('source', 'current', 'seqpropagator', 'propagator0', 'propagator1'), name='unique_correlator_baryonseq3pt'),
        ),
    ]
