# Generated by Django 2.2.2 on 2019-08-26 22:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeSmear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unsmeared',
            fields=[
                ('gaugesmear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gaugesmear.GaugeSmear')),
            ],
            options={
                'abstract': False,
            },
            bases=('gaugesmear.gaugesmear',),
        ),
        migrations.CreateModel(
            name='WilsonFlow',
            fields=[
                ('gaugesmear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gaugesmear.GaugeSmear')),
                ('flowtime', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Flow time in lattice units', max_digits=10)),
                ('flowstep', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Number of diffusion steps')),
            ],
            bases=('gaugesmear.gaugesmear',),
        ),
        migrations.AddConstraint(
            model_name='wilsonflow',
            constraint=models.UniqueConstraint(fields=('flowtime', 'flowstep'), name='unique_gaugesmear_wilsonflow'),
        ),
    ]
