SECRET_KEY: s5icy)=l+((ds60p!+)ypf@8!ey))bb^(mf0v(0&kd=ut!xfbu
PROJECT_APPS:
    - lattedb.base
    - lattedb.status
    - lattedb.action
    - lattedb.ensemble
    - lattedb.gaugesmear
    - lattedb.propagator
    - lattedb.hadron
    - lattedb.hadronsmear
    - lattedb.current
    - lattedb.correlator
    - lattedb.documentation
