SECRET_KEY: s5icy)=l+((ds60p!+)ypf@8!ey))bb^(mf0v(0&kd=ut!xfbu
PROJECT_APPS:
    - lattedb.django.base
    - lattedb.django.status
    - lattedb.django.gaugeconfig
    - lattedb.django.bootstrap
    - lattedb.django.gaugesmear
    - lattedb.django.propagator
    - lattedb.django.hadron
    - lattedb.django.current
    - lattedb.django.correlator
