SECRET_KEY: s5icy)=l+((ds60p!+)ypf@8!ey))bb^(mf0v(0&kd=ut!xfbu
PROJECT_APPS:
    - lattedb.base
    - lattedb.status
    - lattedb.fermionaction
    - lattedb.gaugeaction
    - lattedb.gaugeconfig
    - lattedb.gaugesmear
    - lattedb.project_fhcompare
    - lattedb.propagator
    - lattedb.interpolator
    - lattedb.interpolatorsmear
    - lattedb.current
    - lattedb.correlator
    - lattedb.documentation
    - lattedb.ensemble
ALLOWED_HOSTS:
    - 127.0.0.1
    - ithems.lbl.gov
