# Generated by Django 2.2.2 on 2019-06-24 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('gauge_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hisq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattestructs.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaugeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattestructs.Clover')),
                ('hisq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattestructs.Hisq')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattestructs.Source')),
            ],
        ),
        migrations.AddField(
            model_name='clover',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattestructs.Source'),
        ),
    ]
