# Generated by Django 2.2.2 on 2019-06-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Propagator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gauge_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lattestructs.GaugeConfig')),
            ],
        ),
        migrations.CreateModel(
            name='CloverGaugeConfig',
            fields=[
                ('gaugeconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lattestructs.GaugeConfig')),
                ('lattice_spacing', models.FloatField()),
            ],
            bases=('lattestructs.gaugeconfig',),
        ),
        migrations.CreateModel(
            name='CloverPropagator',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lattestructs.Propagator')),
            ],
            bases=('lattestructs.propagator',),
        ),
        migrations.CreateModel(
            name='HisqGaugeConfig',
            fields=[
                ('gaugeconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lattestructs.GaugeConfig')),
                ('mpi', models.FloatField()),
            ],
            bases=('lattestructs.gaugeconfig',),
        ),
        migrations.CreateModel(
            name='HisqPropagator',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lattestructs.Propagator')),
            ],
            bases=('lattestructs.propagator',),
        ),
    ]
