# Generated by Django 2.2.2 on 2019-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='label',
            field=models.CharField(default='test', help_text='(Optional) Char(20): label to identify ensemble for easy searches', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
