# Generated by Django 2.2.1 on 2019-09-05 23:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FermionAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hisq',
            fields=[
                ('fermionaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fermionaction.FermionAction')),
                ('quark_mass', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Input quark mass', max_digits=10)),
                ('quark_tag', models.TextField(help_text='Text: Type of quark')),
                ('naik', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Coefficient of Naik term. If Naik term is not included, explicitly set to 0', max_digits=10)),
            ],
            bases=('fermionaction.fermionaction',),
        ),
        migrations.CreateModel(
            name='MobiusDW',
            fields=[
                ('fermionaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fermionaction.FermionAction')),
                ('quark_mass', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Input quark mass', max_digits=10)),
                ('quark_tag', models.TextField(help_text='Text: Type of quark')),
                ('l5', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Length of 5th dimension')),
                ('m5', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): 5th dimensional mass', max_digits=10)),
                ('b5', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Mobius kernel parameter [a5 = b5 - c5, alpha5 * a5 = b5 + c5]', max_digits=10)),
                ('c5', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Mobius kernal perameter', max_digits=10)),
            ],
            bases=('fermionaction.fermionaction',),
        ),
        migrations.AddConstraint(
            model_name='mobiusdw',
            constraint=models.UniqueConstraint(fields=('quark_mass', 'quark_tag', 'l5', 'm5', 'b5', 'c5'), name='unique_fermionaction_mobiusdw'),
        ),
        migrations.AddConstraint(
            model_name='hisq',
            constraint=models.UniqueConstraint(fields=('quark_mass', 'quark_tag', 'naik'), name='unique_fermionaction_hisq'),
        ),
    ]
