# Generated by Django 2.2.2 on 2019-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermionaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fermionaction',
            name='unique_fermionaction',
        ),
        migrations.AddConstraint(
            model_name='fermionaction',
            constraint=models.UniqueConstraint(fields=('quark_mass', 'quark_tag', 'type'), name='unique_fermionaction'),
        ),
    ]
