# Generated by Django 2.2.2 on 2019-09-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaugesmear', '0001_initial'),
        ('fermionaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisq',
            name='linksmear',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to additional gauge link smearing outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='gaugesmear.GaugeSmear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiusdw',
            name='linksmear',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to additional gauge link smearing outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='gaugesmear.GaugeSmear'),
            preserve_default=False,
        ),
    ]
