# Generated by Django 2.2.2 on 2019-08-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermionaction', '0002_auto_20190827_1513'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mobiusdw',
            name='unique_fermionaction_mobiusdw',
        ),
        migrations.RemoveField(
            model_name='mobiusdw',
            name='a5',
        ),
        migrations.RemoveField(
            model_name='mobiusdw',
            name='alpha5',
        ),
        migrations.AddConstraint(
            model_name='mobiusdw',
            constraint=models.UniqueConstraint(fields=('fermionaction_ptr_id', 'l5', 'm5', 'b5', 'c5'), name='unique_fermionaction_mobiusdw'),
        ),
    ]
