# Generated by Django 2.2.2 on 2019-08-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fermionaction', '0003_auto_20190827_2157'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fermionaction',
            name='unique_fermionaction',
        ),
        migrations.RemoveConstraint(
            model_name='hisq',
            name='unique_fermionaction_hisq',
        ),
        migrations.RemoveConstraint(
            model_name='mobiusdw',
            name='unique_fermionaction_mobiusdw',
        ),
        migrations.RemoveField(
            model_name='fermionaction',
            name='quark_mass',
        ),
        migrations.RemoveField(
            model_name='fermionaction',
            name='quark_tag',
        ),
        migrations.AddField(
            model_name='hisq',
            name='quark_mass',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Decimal(10,6): Input quark mass', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisq',
            name='quark_tag',
            field=models.TextField(default=1, help_text='Text: Type of quark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiusdw',
            name='quark_mass',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Decimal(10,6): Input quark mass', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiusdw',
            name='quark_tag',
            field=models.TextField(default=1, help_text='Text: Type of quark'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hisq',
            constraint=models.UniqueConstraint(fields=('quark_mass', 'quark_tag', 'naik'), name='unique_fermionaction_hisq'),
        ),
        migrations.AddConstraint(
            model_name='mobiusdw',
            constraint=models.UniqueConstraint(fields=('quark_mass', 'quark_tag', 'l5', 'm5', 'b5', 'c5'), name='unique_fermionaction_mobiusdw'),
        ),
    ]
