# Generated by Django 2.2.1 on 2019-07-02 05:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Basak',
            fields=[
                ('hadron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hadron.Hadron')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('hadron', models.CharField(help_text='Char(20): Hadron name', max_length=20)),
                ('lambda_index', models.CharField(help_text='Char(10): Irreducible representations of O^D_h (improper point group)', max_length=10)),
                ('k_index', models.CharField(help_text='Char(1): k-th representation of O^D_h irrep.', max_length=1)),
                ('spin', models.CharField(help_text='Char(3): Total spin', max_length=3)),
                ('spin_z', models.CharField(help_text='Char(3): Spin in z-direction', max_length=3)),
                ('smearing', models.CharField(blank=True, help_text='(Optional) Char(255): Operator smearing', max_length=255)),
                ('description', models.TextField(blank=True, help_text='(Optional) Text: Description of the interpolating operator')),
            ],
            bases=('hadron.hadron',),
        ),
        migrations.AddConstraint(
            model_name='basak',
            constraint=models.UniqueConstraint(fields=('hadron', 'lambda_index', 'k_index', 'spin', 'spin_z', 'smearing'), name='unique_hadron_basak'),
        ),
    ]
