# Generated by Django 2.2.2 on 2019-08-26 22:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('beta', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Coupling constant', max_digits=10)),
                ('a_fm', models.DecimalField(decimal_places=6, help_text='(Optional) Decimal(10,6): Lattice spacing in fermi', max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LuescherWeisz',
            fields=[
                ('gaugeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gaugeaction.GaugeAction')),
                ('u0', models.DecimalField(decimal_places=6, help_text='Decimal(10,6): Tadpole improvement coefficient', max_digits=10)),
            ],
            bases=('gaugeaction.gaugeaction',),
        ),
        migrations.AddConstraint(
            model_name='luescherweisz',
            constraint=models.UniqueConstraint(fields=('gaugeaction_ptr_id', 'u0'), name='unique_gaugeaction_luescherweisz'),
        ),
        migrations.AddConstraint(
            model_name='gaugeaction',
            constraint=models.UniqueConstraint(fields=('beta',), name='unique_gaugeaction'),
        ),
    ]
