# Generated by Django 2.2.2 on 2019-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gaugeaction',
            name='unique_gaugeaction',
        ),
        migrations.AddConstraint(
            model_name='gaugeaction',
            constraint=models.UniqueConstraint(fields=('beta', 'type'), name='unique_gaugeaction'),
        ),
    ]
