# Generated by Django 2.2.2 on 2019-08-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeaction', '0002_auto_20190827_1529'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gaugeaction',
            name='unique_gaugeaction',
        ),
        migrations.RemoveConstraint(
            model_name='luescherweisz',
            name='unique_gaugeaction_luescherweisz',
        ),
        migrations.RemoveField(
            model_name='gaugeaction',
            name='a_fm',
        ),
        migrations.RemoveField(
            model_name='gaugeaction',
            name='beta',
        ),
        migrations.AddField(
            model_name='luescherweisz',
            name='a_fm',
            field=models.DecimalField(decimal_places=6, help_text='(Optional) Decimal(10,6): Lattice spacing in fermi', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='luescherweisz',
            name='beta',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Decimal(10,6): Coupling constant', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='luescherweisz',
            constraint=models.UniqueConstraint(fields=('beta', 'u0'), name='unique_gaugeaction_luescherweisz'),
        ),
    ]
