# Generated by Django 2.2.2 on 2019-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baryon2pt',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Does not exist'), (2, 'Exists'), (3, 'On tape')], help_text='PositiveSmallInt: Encode categorical status labels', null=True),
        ),
    ]
