# Generated by Django 2.2.2 on 2019-09-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correlator_baryonfh3pt',
            name='correlator',
        ),
        migrations.RemoveField(
            model_name='correlator_baryonfh3pt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='correlator_baryonseq3pt',
            name='correlator',
        ),
        migrations.RemoveField(
            model_name='correlator_baryonseq3pt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='correlator_dwftuning',
            name='correlator',
        ),
        migrations.RemoveField(
            model_name='correlator_dwftuning',
            name='user',
        ),
        migrations.RemoveField(
            model_name='correlator_meson2pt',
            name='correlator',
        ),
        migrations.RemoveField(
            model_name='correlator_meson2pt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ensemble_flavor211',
            name='gaugeconfig',
        ),
        migrations.RemoveField(
            model_name='ensemble_flavor211',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propagator_coherentseq',
            name='propagator',
        ),
        migrations.RemoveField(
            model_name='propagator_coherentseq',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propagator_feynmanhellmann',
            name='propagator',
        ),
        migrations.RemoveField(
            model_name='propagator_feynmanhellmann',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propagator_onetoall',
            name='propagator',
        ),
        migrations.RemoveField(
            model_name='propagator_onetoall',
            name='user',
        ),
        migrations.DeleteModel(
            name='Correlator_Baryon2pt',
        ),
        migrations.DeleteModel(
            name='Correlator_BaryonFH3pt',
        ),
        migrations.DeleteModel(
            name='Correlator_BaryonSeq3pt',
        ),
        migrations.DeleteModel(
            name='Correlator_DWFTuning',
        ),
        migrations.DeleteModel(
            name='Correlator_Meson2pt',
        ),
        migrations.DeleteModel(
            name='Ensemble_Flavor211',
        ),
        migrations.DeleteModel(
            name='Propagator_CoherentSeq',
        ),
        migrations.DeleteModel(
            name='Propagator_FeynmanHellmann',
        ),
        migrations.DeleteModel(
            name='Propagator_OneToAll',
        ),
    ]
