# Generated by Django 2.2.2 on 2019-09-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190906_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baryon2pt',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='baryon2pt',
            name='hdf5path',
        ),
        migrations.AddField(
            model_name='baryon2pt',
            name='dset_path',
            field=models.TextField(blank=True, help_text='(Optional) Text: Path to dset in hdf5 file', null=True),
        ),
        migrations.AddField(
            model_name='baryon2pt',
            name='file_path',
            field=models.TextField(blank=True, help_text='(Optional) Text: Path to hdf5 file', null=True),
        ),
    ]
