# Generated by Django 2.2.2 on 2019-09-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190906_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baryon2pt',
            old_name='barryon2pt',
            new_name='baryon2pt',
        ),
    ]
