# Generated by Django 2.2.2 on 2019-10-05 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20191003_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The group of users how are allowed to read this notification', related_name='notifications', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='The users who have read the notification', related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, help_text='A tag for fast searches', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the notification', max_length=200, null=True),
        ),
    ]
