# Generated by Django 2.2.1 on 2019-07-02 05:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaugesmear', '0001_initial'),
        ('hadron', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('current', '0001_initial'),
        ('gaugeconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propagator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobiusDWF',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('mval', models.DecimalField(decimal_places=6, help_text='Decimal(7,6): Input valence quark mass', max_digits=7)),
                ('l5', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Length of 5th dimension')),
                ('m5', models.DecimalField(decimal_places=2, help_text='Decimal(3,2): 5th dimensional mass', max_digits=3)),
                ('alpha5', models.DecimalField(decimal_places=2, help_text='Decimal(3,2): Mobius coefficient [D_mobius(M5) = alpha5 * D_Shamir(M5)]', max_digits=3)),
                ('a5', models.DecimalField(decimal_places=2, help_text='Decimal(3,2): Mobius kernel parameter [D_mobius = alpha5 * a5 * D_Wilson / (2 + a5 * D_Wilson)]', max_digits=3)),
                ('b5', models.DecimalField(decimal_places=2, help_text='Decimal(3,2): Mobius kernel parameter [a5 = b5 - c5, alpha5 * a5 = b5 + c5]', max_digits=3)),
                ('c5', models.DecimalField(decimal_places=2, help_text='Decimal(3,2): Mobius kernal perameter', max_digits=3)),
                ('origin', models.TextField(help_text='Text: Origin location of the propagator')),
                ('gaugeconfig', models.ForeignKey(help_text='ForeignKey pointing to gauge field', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig')),
                ('gaugesmear', models.ForeignKey(help_text='ForeignKey pointing to gauge link smearing', on_delete=django.db.models.deletion.CASCADE, to='gaugesmear.GaugeSmear')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.CreateModel(
            name='Hisq',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('mval', models.DecimalField(decimal_places=6, help_text='Decimal(7,6): Input valence quark mass', max_digits=7)),
                ('naik', models.DecimalField(decimal_places=6, help_text='Decimal(7,6): Coefficient of Naik term. If Naik term is not included, explicitly set to 0', max_digits=7)),
                ('origin', models.TextField(help_text='Text: Origin location of the propagator')),
                ('gaugeconfig', models.ForeignKey(help_text='ForeignKey pointing to gauge field', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaugeconfig.GaugeConfig')),
                ('gaugesmear', models.ForeignKey(help_text='ForeignKey pointing to gauge link smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaugesmear.GaugeSmear')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.CreateModel(
            name='FeynmanHellmann',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('momentum', models.SmallIntegerField(help_text='SmallInt: Current insertion momentum in units of 2 pi / L')),
                ('current', models.ForeignKey(help_text='ForeignKey linking current insertion operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='current.Current')),
                ('propagator0', models.ForeignKey(help_text='ForeignKey linking source side propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='ForeignKey linking sink side propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.CreateModel(
            name='CoherentSeq',
            fields=[
                ('propagator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propagator.Propagator')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('groupsize', models.PositiveSmallIntegerField(help_text='PositiveSmallint: Total number of propagators sharing a coherent sink')),
                ('groupindex', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: A group index indicating which coherent sink group the propagator belongs to')),
                ('sinksep', models.SmallIntegerField(help_text='SmallInt: Source-sink separation time')),
                ('momentum', models.SmallIntegerField(help_text='SmallInt: Sink momentum in units of 2 pi / L')),
                ('propagator', models.ForeignKey(help_text='ForeignKey that link to a coherent propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sink', models.ForeignKey(help_text='ForeignKey: Pointer to sink interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hadron.Hadron')),
            ],
            bases=('propagator.propagator',),
        ),
        migrations.AddConstraint(
            model_name='mobiusdwf',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'gaugesmear', 'mval', 'l5', 'm5', 'alpha5', 'a5', 'b5', 'c5', 'origin'), name='unique_propagator_mobiusdwf'),
        ),
        migrations.AddConstraint(
            model_name='hisq',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'gaugesmear', 'mval', 'naik', 'origin'), name='unique_propagator_hisq'),
        ),
        migrations.AddConstraint(
            model_name='feynmanhellmann',
            constraint=models.UniqueConstraint(fields=('propagator0', 'current', 'propagator1', 'momentum'), name='unique_propagator_feynmanhellmann'),
        ),
        migrations.AddConstraint(
            model_name='coherentseq',
            constraint=models.UniqueConstraint(fields=('propagator', 'groupsize', 'groupindex', 'sink', 'sinksep', 'momentum'), name='unique_propagator_coherentseq'),
        ),
    ]
