# Generated by Django 2.2.2 on 2019-09-04 18:41

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correlator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fhcompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mn', models.FloatField(help_text='Float: nucleon mass')),
                ('ga', models.FloatField(help_text='Float: axial charge')),
                ('gv', models.FloatField(help_text='Float: vector charge')),
                ('rating', models.SmallIntegerField(default=1, help_text='Int: Limit from 1 to 5, default = 1. Rate your own fits.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(help_text="JSON: {'your_results': 'all dumped here'}")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceAvg2pt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlators', models.ManyToManyField(to='correlator.Baryon2pt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jason0',
            fields=[
                ('fhcompare_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project_fhcompare.Fhcompare')),
                ('tmin2pt', models.SmallIntegerField()),
                ('tmax2pt', models.SmallIntegerField()),
                ('tminfhga', models.SmallIntegerField()),
                ('tmaxfhga', models.SmallIntegerField()),
                ('tminfhgv', models.SmallIntegerField()),
                ('tmaxfhgv', models.SmallIntegerField()),
                ('tminseqga', models.SmallIntegerField()),
                ('tmaxseqga', models.SmallIntegerField()),
                ('uminseqga', models.SmallIntegerField()),
                ('umaxseqga', models.SmallIntegerField()),
                ('tminseqgv', models.SmallIntegerField()),
                ('tmaxseqgv', models.SmallIntegerField()),
                ('uminseqgv', models.SmallIntegerField()),
                ('umaxseqgv', models.SmallIntegerField()),
                ('nstates', models.SmallIntegerField()),
                ('fstates', models.SmallIntegerField()),
                ('corr2pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrfhga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrfhgv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrseqga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrseqgv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
            ],
            bases=('project_fhcompare.fhcompare',),
        ),
        migrations.AddConstraint(
            model_name='jason0',
            constraint=models.UniqueConstraint(fields=('corr2pt', 'corrfhga', 'corrfhgv', 'corrseqga', 'corrseqgv', 'tmin2pt', 'tmax2pt', 'tminfhga', 'tmaxfhga', 'tminfhgv', 'tmaxfhgv', 'tminseqga', 'tmaxseqga', 'uminseqga', 'umaxseqga', 'tminseqgv', 'tmaxseqgv', 'uminseqgv', 'umaxseqgv', 'nstates', 'fstates'), name='unique_project_fhcompare_jason0'),
        ),
    ]
