# Generated by Django 2.2.1 on 2019-09-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_fhcompare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceavg2pt',
            old_name='correlators',
            new_name='baryon2pts',
        ),
    ]
