# Generated by Django 2.2.1 on 2019-09-14 01:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_fhcompare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jason0',
            name='unique_project_fhcompare_jason0',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='fstates',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='nstates',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tmax2pt',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tmaxfhga',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tmaxfhgv',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tmaxseqga',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tmaxseqgv',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tmin2pt',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tminfhga',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tminfhgv',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tminseqga',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='tminseqgv',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='umaxseqga',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='umaxseqgv',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='uminseqga',
        ),
        migrations.RemoveField(
            model_name='jason0',
            name='uminseqgv',
        ),
        migrations.AddField(
            model_name='jason0',
            name='hash_fit',
            field=models.TextField(default='', help_text='Unique hash field to prevent writing in same result'),
        ),
        migrations.AddField(
            model_name='jason0',
            name='inputs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Other inputs (priors, etc...), enters in hash'),
        ),
        migrations.AddField(
            model_name='jason0',
            name='states',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Dictionary of nstates, enters in hash'),
        ),
        migrations.AddField(
            model_name='jason0',
            name='trange',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Dictionary of time ranges, this goes into creating the hash'),
        ),
        migrations.AddConstraint(
            model_name='jason0',
            constraint=models.UniqueConstraint(fields=('corr2pt', 'corrfhga', 'corrfhgv', 'corrseqga', 'corrseqgv', 'hash_fit'), name='unique_project_fhcompare_jason0'),
        ),
    ]
