# Generated by Django 2.2.2 on 2019-09-04 18:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_fhcompare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhcompare',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fhcompare',
            name='misc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True),
        ),
        migrations.AddField(
            model_name='fhcompare',
            name='tag',
            field=models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fhcompare',
            name='type',
            field=models.TextField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fhcompare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourceavg2pt',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sourceavg2pt',
            name='misc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True),
        ),
        migrations.AddField(
            model_name='sourceavg2pt',
            name='tag',
            field=models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sourceavg2pt',
            name='type',
            field=models.TextField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceavg2pt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fhcompare',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sourceavg2pt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
