# Generated by Django 2.2.1 on 2019-09-14 01:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_fhcompare', '0002_auto_20190914_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jason0',
            name='inputs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Other inputs (priors, etc...), enters in hash'),
        ),
        migrations.AlterField(
            model_name='jason0',
            name='states',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary of nstates, enters in hash'),
        ),
        migrations.AlterField(
            model_name='jason0',
            name='trange',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary of time ranges, this goes into creating the hash'),
        ),
    ]
