# Generated by Django 2.2.1 on 2019-09-05 22:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_fhcompare', '0002_auto_20190905_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceavg2pt',
            name='imag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], help_text='Float: Imaginary part of correlator', size=None),
        ),
        migrations.AddField(
            model_name='sourceavg2pt',
            name='real',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], help_text='Float: Real part of correlator', size=None),
        ),
    ]
