# Generated by Django 2.2.1 on 2019-09-05 22:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_fhcompare', '0003_auto_20190905_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceavg2pt',
            name='imag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Float: Imaginary part of correlator', size=None),
        ),
        migrations.AlterField(
            model_name='sourceavg2pt',
            name='real',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Float: Real part of correlator', size=None),
        ),
    ]
