# Generated by Django 2.2.2 on 2019-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propagator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propagator',
            name='unique_propagator',
        ),
        migrations.AddConstraint(
            model_name='propagator',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'type'), name='unique_propagator'),
        ),
    ]
