# Generated by Django 2.2.2 on 2019-08-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fermionaction', '0003_auto_20190827_2157'),
        ('gaugeconfig', '0004_remove_gaugeconfig_l_fm'),
        ('propagator', '0002_auto_20190827_1529'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coherentseq',
            name='unique_propagator_coherentseq',
        ),
        migrations.RemoveConstraint(
            model_name='feynmanhellmann',
            name='unique_propagator_feynmanhellmann',
        ),
        migrations.RemoveConstraint(
            model_name='onetoall',
            name='unique_propagator_onetoall',
        ),
        migrations.RemoveConstraint(
            model_name='propagator',
            name='unique_propagator',
        ),
        migrations.RemoveField(
            model_name='propagator',
            name='fermionaction',
        ),
        migrations.RemoveField(
            model_name='propagator',
            name='gaugeconfig',
        ),
        migrations.AddField(
            model_name='coherentseq',
            name='fermionaction',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to valence lattice fermion action', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coherentseq',
            name='gaugeconfig',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to specific gauge configuration inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feynmanhellmann',
            name='fermionaction',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to valence lattice fermion action', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feynmanhellmann',
            name='gaugeconfig',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to specific gauge configuration inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetoall',
            name='fermionaction',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to valence lattice fermion action', on_delete=django.db.models.deletion.CASCADE, to='fermionaction.FermionAction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetoall',
            name='gaugeconfig',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to specific gauge configuration inverted on', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.GaugeConfig'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='coherentseq',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'propagator0', 'propagator1', 'groupsize', 'groupindex', 'sink', 'sinksep'), name='unique_propagator_coherentseq'),
        ),
        migrations.AddConstraint(
            model_name='feynmanhellmann',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'propagator', 'current'), name='unique_propagator_feynmanhellmann'),
        ),
        migrations.AddConstraint(
            model_name='onetoall',
            constraint=models.UniqueConstraint(fields=('gaugeconfig', 'fermionaction', 'origin_x', 'origin_y', 'origin_z', 'origin_t'), name='unique_propagator_onetoall'),
        ),
    ]
