# Generated by Django 2.2.2 on 2019-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eigenvalue',
            name='n_level',
            field=models.PositiveIntegerField(help_text='The nth eigenvalue extracted in ascending order.'),
        ),
        migrations.AlterField(
            model_name='eigenvalue',
            name='value',
            field=models.FloatField(help_text='The value of the eigenvalue'),
        ),
        migrations.AlterField(
            model_name='exteranlfieldisingmodel',
            name='h',
            field=models.DecimalField(decimal_places=3, help_text='Implements uniform magnetic field: Implements uniform nearest neighbor interactions: \\(-\\mu \\sum_{j} h_j \\sigma_j = -\\mu h \\sum_{j} \\sigma_j\\)', max_digits=5, verbose_name='External magnetic field'),
        ),
        migrations.AlterField(
            model_name='exteranlfieldisingmodel',
            name='j',
            field=models.DecimalField(decimal_places=3, help_text='Interaction parameter of th the Ising Model. Implements uniform nearest neighbor interactions: \\( -\\sum_{NN} J_{ij} \\sigma_i \\sigma_j = -J\\sum_{NN} \\sigma_i \\sigma_j \\)', max_digits=5, verbose_name='Interaction'),
        ),
        migrations.AlterField(
            model_name='isingmodel',
            name='j',
            field=models.DecimalField(decimal_places=3, help_text='Interaction parameter of th the Ising Model. Implements uniform nearest neighbor interactions: \\( -\\sum_{NN} J_{ij} \\sigma_i \\sigma_j = -J\\sum_{NN} \\sigma_i \\sigma_j \\)', max_digits=5, verbose_name='Interaction'),
        ),
    ]
