# Generated by Django 2.2.2 on 2019-09-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20190930_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eigenvalue',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='spinhamiltonian',
            name='misc',
        ),
    ]
