# Generated by Django 2.2.1 on 2019-07-02 05:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('current_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='current.Current')),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20)),
                ('diracstruct', models.CharField(help_text='Char(20): Dirac structure of the current', max_length=20)),
                ('flavor0', models.CharField(blank=True, help_text='(Optional) Char(1): Incoming quark field flavor. Useful to specify for nucleons.', max_length=1)),
                ('flavor1', models.CharField(blank=True, help_text='(Optional) Char(1): Outgoing quark field flavor. Useful to specify for nucleons.', max_length=1)),
                ('description', models.TextField(blank=True, help_text='(Optional) Text: Description of current')),
            ],
            bases=('current.current',),
        ),
        migrations.AddConstraint(
            model_name='local',
            constraint=models.UniqueConstraint(fields=('diracstruct', 'flavor0', 'flavor1'), name='unique_current_local'),
        ),
    ]
