# Generated by Django 2.2.1 on 2019-09-05 17:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interpolatorsmear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpolator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hadron4D',
            fields=[
                ('interpolator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interpolator.Interpolator')),
                ('description', models.TextField(blank=True, help_text='(Optional) Text: Description of the interpolating operator', null=True)),
                ('strangeness', models.PositiveSmallIntegerField(help_text='PositiveSmallIntegerField: Strangeness of hadronic operator')),
                ('irrep', models.TextField(help_text='Text: Irreducible representations of O^D_h (octahedral group)')),
                ('embedding', models.PositiveSmallIntegerField(help_text='PositiveSmallIntegerField: k-th embedding of O^D_h irrep.')),
                ('parity', models.SmallIntegerField(help_text='SmallIntegerField: Parity of hadronic operator')),
                ('spin_x2', models.PositiveSmallIntegerField(help_text='Text: Total spin times two')),
                ('spin_z_x2', models.SmallIntegerField(help_text='Text: Spin in z-direction')),
                ('isospin_x2', models.PositiveSmallIntegerField(help_text='Text: Total isospin times two')),
                ('isospin_z_x2', models.SmallIntegerField(help_text='Text: Isospin in z-direction times two')),
                ('interpolatorsmear', models.ForeignKey(help_text='ForeignKey pointing to operator smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolatorsmear.InterpolatorSmear')),
            ],
            bases=('interpolator.interpolator',),
        ),
        migrations.CreateModel(
            name='Hadron',
            fields=[
                ('interpolator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interpolator.Interpolator')),
                ('description', models.TextField(blank=True, help_text='(Optional) Text: Description of the interpolating operator', null=True)),
                ('strangeness', models.PositiveSmallIntegerField(help_text='PositiveSmallIntegerField: Strangeness of hadronic operator')),
                ('irrep', models.TextField(help_text='Text: Irreducible representations of O^D_h (octahedral group)')),
                ('embedding', models.PositiveSmallIntegerField(help_text='PositiveSmallIntegerField: k-th embedding of O^D_h irrep.')),
                ('parity', models.SmallIntegerField(help_text='SmallIntegerField: Parity of hadronic operator')),
                ('spin_x2', models.PositiveSmallIntegerField(help_text='Text: Total spin times two')),
                ('spin_z_x2', models.SmallIntegerField(help_text='Text: Spin in z-direction')),
                ('isospin_x2', models.PositiveSmallIntegerField(help_text='Text: Total isospin times two')),
                ('isospin_z_x2', models.SmallIntegerField(help_text='Text: Isospin in z-direction times two')),
                ('momentum', models.SmallIntegerField(help_text='SmallInt: Momentum in units of 2 pi / L')),
                ('interpolatorsmear', models.ForeignKey(help_text='ForeignKey pointing to operator smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolatorsmear.InterpolatorSmear')),
            ],
            bases=('interpolator.interpolator',),
        ),
        migrations.AddConstraint(
            model_name='hadron4d',
            constraint=models.UniqueConstraint(fields=('interpolatorsmear', 'strangeness', 'irrep', 'embedding', 'parity', 'spin_x2', 'spin_z_x2', 'isospin_x2', 'isospin_z_x2'), name='unique_hadron_hadron4d'),
        ),
        migrations.AddConstraint(
            model_name='hadron',
            constraint=models.UniqueConstraint(fields=('interpolatorsmear', 'strangeness', 'irrep', 'embedding', 'parity', 'spin_x2', 'spin_z_x2', 'isospin_x2', 'isospin_z_x2', 'momentum'), name='unique_hadron_hadron'),
        ),
    ]
