# Generated by Django 2.2.1 on 2019-08-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpolator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadron',
            name='parity',
            field=models.SmallIntegerField(help_text='SmallIntegerField: Parity of hadronic operator'),
        ),
        migrations.AlterField(
            model_name='hadron4d',
            name='parity',
            field=models.SmallIntegerField(help_text='SmallIntegerField: Parity of hadronic operator'),
        ),
    ]
