# Generated by Django 2.2.2 on 2019-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpolator', '0002_auto_20190826_2353'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interpolator',
            name='unique_interpolator',
        ),
        migrations.AddConstraint(
            model_name='interpolator',
            constraint=models.UniqueConstraint(fields=('interpolatorsmear', 'strangeness', 'type'), name='unique_interpolator'),
        ),
    ]
