# Generated by Django 2.2.2 on 2019-08-28 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interpolatorsmear', '0001_initial'),
        ('interpolator', '0003_auto_20190827_1529'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hadron',
            name='unique_hadron_hadron',
        ),
        migrations.RemoveConstraint(
            model_name='hadron4d',
            name='unique_hadron_hadron4d',
        ),
        migrations.RemoveConstraint(
            model_name='interpolator',
            name='unique_interpolator',
        ),
        migrations.RemoveField(
            model_name='interpolator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interpolator',
            name='interpolatorsmear',
        ),
        migrations.RemoveField(
            model_name='interpolator',
            name='strangeness',
        ),
        migrations.AddField(
            model_name='hadron',
            name='description',
            field=models.TextField(blank=True, help_text='(Optional) Text: Description of the interpolating operator', null=True),
        ),
        migrations.AddField(
            model_name='hadron',
            name='interpolatorsmear',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to operator smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolatorsmear.InterpolatorSmear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadron',
            name='strangeness',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallIntegerField: Strangeness of hadronic operator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadron4d',
            name='description',
            field=models.TextField(blank=True, help_text='(Optional) Text: Description of the interpolating operator', null=True),
        ),
        migrations.AddField(
            model_name='hadron4d',
            name='interpolatorsmear',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to operator smearing', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolatorsmear.InterpolatorSmear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hadron4d',
            name='strangeness',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallIntegerField: Strangeness of hadronic operator'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hadron',
            constraint=models.UniqueConstraint(fields=('interpolatorsmear', 'strangeness', 'irrep', 'embedding', 'parity', 'spin_x2', 'spin_z_x2', 'isospin_x2', 'isospin_z_x2', 'momentum'), name='unique_hadron_hadron'),
        ),
        migrations.AddConstraint(
            model_name='hadron4d',
            constraint=models.UniqueConstraint(fields=('interpolatorsmear', 'strangeness', 'irrep', 'embedding', 'parity', 'spin_x2', 'spin_z_x2', 'isospin_x2', 'isospin_z_x2'), name='unique_hadron_hadron4d'),
        ),
    ]
