# Generated by Django 2.2.1 on 2019-07-02 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correlator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gaugeconfig', '0001_initial'),
        ('propagator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propagator_MobiusDWF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('propagator', models.ForeignKey(help_text='ForeignKey to HISQ propagator table', on_delete=django.db.models.deletion.CASCADE, to='propagator.MobiusDWF')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propagator_Hisq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('propagator', models.ForeignKey(help_text='ForeignKey to HISQ propagator table', on_delete=django.db.models.deletion.CASCADE, to='propagator.Hisq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propagator_FeynmanHellmann',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('propagator', models.ForeignKey(help_text='ForeignKey to Feynman-Hellmann propagator table', on_delete=django.db.models.deletion.CASCADE, to='propagator.FeynmanHellmann')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propagator_CoherentSeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('propagator', models.ForeignKey(help_text='ForeignKey to coherent sequential propagator table', on_delete=django.db.models.deletion.CASCADE, to='propagator.CoherentSeq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GaugeConfig_Hisq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('gaugeconfig', models.ForeignKey(help_text='ForeignKey pointing to HISQ ensemble', on_delete=django.db.models.deletion.CASCADE, to='gaugeconfig.Hisq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Correlator_Meson2pt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('correlator', models.ForeignKey(help_text='ForeignKey pointing to meson two point correlation function', on_delete=django.db.models.deletion.CASCADE, to='correlator.Meson2pt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Correlator_BaryonFH3pt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('correlator', models.ForeignKey(help_text='Foreign Key to a Feynman-Hellmann three point correlation function', on_delete=django.db.models.deletion.CASCADE, to='correlator.BaryonFH3pt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Correlator_Baryon4DSeq3pt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('home', models.CharField(blank=True, help_text='(Optional) Char(20): Computing facility where the object resides at', max_length=20)),
                ('runscript', models.TextField(blank=True, help_text='(Optional) Text: Path to, or content of run script')),
                ('directory', models.TextField(blank=True, help_text='(Optional) Text: Directory path to result')),
                ('hdf5path', models.TextField(blank=True, help_text='(Optional) Text: Folder path in hdf5 file')),
                ('size', models.IntegerField(help_text='(Optional) Int: file size', null=True)),
                ('statusencoder', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Encode categorical status labels with values between 0 and n_classes-1')),
                ('correlator', models.ForeignKey(help_text='Foreign Key to a sequential three point correlation function', on_delete=django.db.models.deletion.CASCADE, to='correlator.Baryon4DSeq3pt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='propagator_mobiusdwf',
            constraint=models.UniqueConstraint(fields=('propagator',), name='unique_status_propagator_mobiusdwf'),
        ),
        migrations.AddConstraint(
            model_name='propagator_hisq',
            constraint=models.UniqueConstraint(fields=('propagator',), name='unique_status_propagator_hisq'),
        ),
        migrations.AddConstraint(
            model_name='propagator_feynmanhellmann',
            constraint=models.UniqueConstraint(fields=('propagator',), name='unique_status_propagator_feynmanhellmann'),
        ),
        migrations.AddConstraint(
            model_name='propagator_coherentseq',
            constraint=models.UniqueConstraint(fields=('propagator',), name='unique_status_propagator_coherentseq'),
        ),
        migrations.AddConstraint(
            model_name='gaugeconfig_hisq',
            constraint=models.UniqueConstraint(fields=('gaugeconfig',), name='unique_status_gaugeconfig_hisq'),
        ),
        migrations.AddConstraint(
            model_name='correlator_meson2pt',
            constraint=models.UniqueConstraint(fields=('correlator',), name='unique_status_correlator_meson2pt'),
        ),
        migrations.AddConstraint(
            model_name='correlator_baryonfh3pt',
            constraint=models.UniqueConstraint(fields=('correlator',), name='unique_status_correlator_baryonfh3pt'),
        ),
        migrations.AddConstraint(
            model_name='correlator_baryon4dseq3pt',
            constraint=models.UniqueConstraint(fields=('correlator',), name='unique_status_correlator_baryon4dseq3pt'),
        ),
    ]
