# Generated by Django 2.2.2 on 2019-08-26 22:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correlator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Fhcompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('mn', models.FloatField(help_text='Float: nucleon mass')),
                ('ga', models.FloatField(help_text='Float: axial charge')),
                ('gv', models.FloatField(help_text='Float: vector charge')),
                ('rating', models.SmallIntegerField(default=1, help_text='Int: Limit from 1 to 5, default = 1. Rate your own fits.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(help_text="JSON: {'your_results': 'all dumped here'}")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jason0',
            fields=[
                ('project_fhcompare_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project_fhcompare.Project_Fhcompare')),
                ('tmin2pt', models.SmallIntegerField()),
                ('tmax2pt', models.SmallIntegerField()),
                ('tminfhga', models.SmallIntegerField()),
                ('tmaxfhga', models.SmallIntegerField()),
                ('tminfhgv', models.SmallIntegerField()),
                ('tmaxfhgv', models.SmallIntegerField()),
                ('tminseqga', models.SmallIntegerField()),
                ('tmaxseqga', models.SmallIntegerField()),
                ('uminseqga', models.SmallIntegerField()),
                ('umaxseqga', models.SmallIntegerField()),
                ('tminseqgv', models.SmallIntegerField()),
                ('tmaxseqgv', models.SmallIntegerField()),
                ('uminseqgv', models.SmallIntegerField()),
                ('umaxseqgv', models.SmallIntegerField()),
                ('nstates', models.SmallIntegerField()),
                ('fstates', models.SmallIntegerField()),
                ('corr2pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrfhga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrfhgv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrseqga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
                ('corrseqgv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='correlator.Correlator')),
            ],
            bases=('project_fhcompare.project_fhcompare',),
        ),
        migrations.AddConstraint(
            model_name='jason0',
            constraint=models.UniqueConstraint(fields=('corr2pt', 'corrfhga', 'corrfhgv', 'corrseqga', 'corrseqgv', 'tmin2pt', 'tmax2pt', 'tminfhga', 'tmaxfhga', 'tminfhgv', 'tmaxfhgv', 'tminseqga', 'tmaxseqga', 'uminseqga', 'umaxseqga', 'tminseqgv', 'tmaxseqgv', 'uminseqgv', 'umaxseqgv', 'nstates', 'fstates'), name='unique_project_fhcompare_jason0'),
        ),
    ]
