# Generated by Django 2.2.1 on 2019-07-02 05:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hisq',
            fields=[
                ('gaugeconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gaugeconfig.GaugeConfig')),
                ('long_tag', models.TextField(blank=True, help_text="(Optional) Text: Full name for ensemble (e.g. 'l1648f211b580m013m065m838')")),
                ('short_tag', models.CharField(blank=True, help_text="(Optional) Char(20): Short name for ensemble (e.g. 'a15m310')", max_length=20)),
                ('stream', models.CharField(help_text='Charfield(3): Stream tag for Monte Carlo', max_length=3)),
                ('nconfig', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Number of configurations')),
                ('nx', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Spatial length in lattice units')),
                ('nt', models.PositiveSmallIntegerField(help_text='PositiveSmallInt: Temporal length in lattice units')),
                ('ml', models.DecimalField(decimal_places=6, help_text='Decimal(7,6): Input light quark mass', max_digits=7)),
                ('ms', models.DecimalField(decimal_places=5, help_text='Decimal(6,5): Input strange quark mass', max_digits=6)),
                ('mc', models.DecimalField(decimal_places=4, help_text='Decimal(5,4): Input charm quark mass', max_digits=5)),
                ('beta', models.DecimalField(decimal_places=4, help_text='Decimal(6,4): Coupling constant', max_digits=6)),
                ('naik', models.DecimalField(decimal_places=6, help_text='Decimal(7,6): Coefficient of Naik term. If Naik term is not included, explicitly set to 0', max_digits=7)),
                ('u0', models.DecimalField(decimal_places=6, help_text='(Optional) Decimal(7,6): Tadpole improvement coefficient', max_digits=7, null=True)),
                ('a_fm', models.DecimalField(decimal_places=3, help_text='(Optional) Decimal(4,3): Lattice spacing in fermi', max_digits=4, null=True)),
                ('l_fm', models.DecimalField(decimal_places=3, help_text='(Optional) Decimal(5,3): Spatial length in fermi', max_digits=5, null=True)),
                ('mpil', models.DecimalField(decimal_places=3, help_text='(Optional) Decimal(5,3): Spatial length in mpiL', max_digits=5, null=True)),
                ('mpi', models.DecimalField(decimal_places=2, help_text='(Optional) Decimal(5,2): Pion mass in MeV', max_digits=5, null=True)),
            ],
            bases=('gaugeconfig.gaugeconfig',),
        ),
        migrations.AddConstraint(
            model_name='hisq',
            constraint=models.UniqueConstraint(fields=('stream', 'nconfig', 'nx', 'nt', 'ml', 'ms', 'mc', 'beta', 'naik'), name='unique_gaugeconfig_hisq'),
        ),
    ]
