# Generated by Django 2.2.1 on 2019-08-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nf211',
            name='mpil',
        ),
    ]
