# Generated by Django 2.2.2 on 2019-09-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nf211',
            name='gaugesmear',
        ),
    ]
