# Generated by Django 2.2.2 on 2019-08-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeconfig', '0002_remove_nf211_mpil'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gaugeconfig',
            name='unique_gaugeconfig',
        ),
        migrations.AddConstraint(
            model_name='gaugeconfig',
            constraint=models.UniqueConstraint(fields=('stream', 'config', 'gaugeaction', 'nx', 'ny', 'nz', 'nt', 'gaugesmear', 'type'), name='unique_gaugeconfig'),
        ),
    ]
