# Generated by Django 2.2.2 on 2019-08-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaugeconfig', '0003_auto_20190827_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='l_fm',
        ),
    ]
