# Generated by Django 2.2.2 on 2019-08-28 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaugesmear', '0001_initial'),
        ('gaugeaction', '0003_auto_20190828_0040'),
        ('gaugeconfig', '0004_remove_gaugeconfig_l_fm'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gaugeconfig',
            name='unique_gaugeconfig',
        ),
        migrations.RemoveConstraint(
            model_name='nf211',
            name='unique_gaugeconfig_nf211',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='config',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='gaugeaction',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='gaugesmear',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='nt',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='nx',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='ny',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='nz',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='short_tag',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='stream',
        ),
        migrations.AddField(
            model_name='nf211',
            name='config',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallInt: Configuration number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='gaugeaction',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to lattice gauge action', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gaugeaction.GaugeAction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='gaugesmear',
            field=models.ForeignKey(default=1, help_text='ForeignKey pointing to additional gauge link smearing outside of Monte Carlo.', on_delete=django.db.models.deletion.CASCADE, to='gaugesmear.GaugeSmear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='nt',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallInt: Temporal length in lattice units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='nx',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallInt: Spatial length in lattice units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='ny',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallInt: Spatial length in lattice units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='nz',
            field=models.PositiveSmallIntegerField(default=1, help_text='PositiveSmallInt: Spatial length in lattice units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nf211',
            name='short_tag',
            field=models.TextField(blank=True, help_text="(Optional) Text: Short name for gaugeconfig (e.g. 'a15m310')", null=True),
        ),
        migrations.AddField(
            model_name='nf211',
            name='stream',
            field=models.TextField(default=1, help_text='Text: Stream tag for Monte Carlo'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='nf211',
            constraint=models.UniqueConstraint(fields=('stream', 'config', 'gaugeaction', 'nx', 'ny', 'nz', 'nt', 'gaugesmear', 'light', 'strange', 'charm'), name='unique_gaugeconfig_nf211'),
        ),
    ]
