# Generated by Django 2.2.2 on 2019-08-26 22:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interpolator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propagator', '0001_initial'),
        ('current', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(editable=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, help_text='(Optional) Char(20): User defined tag for easy searches', max_length=20, null=True)),
                ('misc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="(Optional) JSON: {'anything': 'you want'}", null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meson2pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('propagator0', models.ForeignKey(help_text='ForeignKey: Pointer to first propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='ForeignKey: Pointer to second propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sink', models.ForeignKey(help_text='ForeignKey: Pointer to sink interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
                ('source', models.ForeignKey(help_text='ForeignKey: Pointer to source interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.CreateModel(
            name='DWFTuning',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('sink5', models.BooleanField(help_text='Boolean: Is the sink on the domain wall?')),
                ('propagator', models.ForeignKey(help_text='ForeignKey: Pointer to first propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('source', models.ForeignKey(help_text='ForeignKey: Pointer to source interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.CreateModel(
            name='BaryonSeq3pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('current', models.ForeignKey(help_text='Foreign Key to current interaction operator', on_delete=django.db.models.deletion.CASCADE, to='current.Current')),
                ('propagator', models.ForeignKey(help_text='Foreign Key pointing to daughter quark', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('seqpropagator', models.ForeignKey(help_text='Foreign Key pointing to sequential propagator (2 spectator quarks + 1 daughter)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('source', models.ForeignKey(help_text='Foreign Key pointing to source operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.CreateModel(
            name='BaryonFH3pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('fhpropagator', models.ForeignKey(help_text='Foreign Key pointing to Feynman-Hellmann propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator0', models.ForeignKey(help_text='Foreign Key pointing to spectator propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='Foreign Key pointing to spectator propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sink', models.ForeignKey(help_text='Foreign Key pointing to sink operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
                ('source', models.ForeignKey(help_text='Foreign Key pointing to source operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.CreateModel(
            name='Baryon2pt',
            fields=[
                ('correlator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correlator.Correlator')),
                ('propagator0', models.ForeignKey(help_text='ForeignKey: Pointer to first propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator1', models.ForeignKey(help_text='ForeignKey: Pointer to second propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('propagator2', models.ForeignKey(help_text='ForeignKey: Pointer to third propagator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='propagator.Propagator')),
                ('sink', models.ForeignKey(help_text='ForeignKey: Pointer to sink interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
                ('source', models.ForeignKey(help_text='ForeignKey: Pointer to source interpolating operator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interpolator.Interpolator')),
            ],
            bases=('correlator.correlator',),
        ),
        migrations.AddConstraint(
            model_name='meson2pt',
            constraint=models.UniqueConstraint(fields=('propagator0', 'propagator1', 'source', 'sink'), name='unique_correlator_meson2pt'),
        ),
        migrations.AddConstraint(
            model_name='dwftuning',
            constraint=models.UniqueConstraint(fields=('propagator', 'source', 'sink5'), name='unique_correlator_dwftuning'),
        ),
        migrations.AddConstraint(
            model_name='baryonseq3pt',
            constraint=models.UniqueConstraint(fields=('source', 'current', 'seqpropagator', 'propagator'), name='unique_correlator_baryonseq3pt'),
        ),
        migrations.AddConstraint(
            model_name='baryonfh3pt',
            constraint=models.UniqueConstraint(fields=('source', 'fhpropagator', 'propagator0', 'propagator1', 'sink'), name='unique_correlator_baryonfh3pt'),
        ),
        migrations.AddConstraint(
            model_name='baryon2pt',
            constraint=models.UniqueConstraint(fields=('propagator0', 'propagator1', 'propagator2', 'source', 'sink'), name='unique_correlator_baryon2pt'),
        ),
    ]
